support for OCI images via buildah (optional, experimental)

diff --git a/sudoexec/jcreate b/sudoexec/jcreate
--- a/sudoexec/jcreate
+++ b/sudoexec/jcreate
@@ -20,6 +20,10 @@ The jail is created according to configuration file generated by jconstruct-tui.
 You can see this configuration file if you answer negatively to the 
 'Do you want to create jail immediately?' question at the end of the dialogue.
 
+If the 'buildah' package is installed on the system, you can use the OCI images 
+(including Linux) from the official docker registry - see the examples section 
+with the [*] marker.
+
 In addition, you can override all parameters via command line arguments.
 Many parameters are set by default via profiles, 
 e.g: ~cbsd/etc/defaults/jail-freebsd-default.conf which can be overwrited via
@@ -49,6 +53,7 @@ ${H3_COLOR}Options${N0_COLOR}:
                    string itself, e.g: ci_user_pubkey=\"ssh-ed25519 XXXXX root@my.domain\".
                    This options will customize /root/.ssh/authorized_keys in jail.
  ${N2_COLOR}ci_gw4=${N0_COLOR}         - 0,IP to disable: manage/set defaultrouter= settings in jail rc.conf (for vnet).
+ ${N2_COLOR}emulator=${N0_COLOR}       - specify emulator engine (e.g. for qemu-user mode or linuxulator;
  ${N2_COLOR}etcupdate_init=${N0_COLOR} - 1(enable),0(disable) for etcupdate init (overwrite config values).
  ${N2_COLOR}flavor${N0_COLOR}          - Use flavor (named group of vm_cpus/vm_ram/imgsize): see 'cbsd vm-packages';
  ${N2_COLOR}from=${N0_COLOR}           - <url> or MD5 of image to create jail from CBSD image.
@@ -73,7 +78,6 @@ Additional args when RACCT enabled: ${RCTL} ${RCTL_EXTRA}
  ${N2_COLOR}vmemoryuse=${N0_COLOR}     - limit memory use, e.g: 512m
 
 
-
 ${H3_COLOR}Examples${N0_COLOR}:
 
  # cbsd jcreate jname=test runasap=1 zfs_encryption=1
@@ -85,9 +89,12 @@ ${H3_COLOR}Examples${N0_COLOR}:
  # cbsd jcreate jname=dev jprofile=devuan_daedalus allow_raw_sockets=1
  # cbsd jcreate jname=riscv pkg_bootstrap=0 arch=riscv emulator=\"qemu-riscv64-static\" exec_start=\"/bin/qemu-riscv64-static /bin/sh /etc/rc\" exec_stop=\"/bin/qemu-riscv64-static /bin/sh /etc/rc.shutdown\"
  # cbsd jcreate jname=xx ver=13.2 vnet=1 sysrc=\"ifconfig_eth0+='mtu 1450' inetd_enable=YES\"
- # cbsd jcreate jname=vmagent from=https://dl.bsdstore.ru/img/amd64/amd64/13.2/vmagent/vmagent.img pkg_bootstrap=0 runasap=1
+ # cbsd jcreate jname=vmagent from=https://dl.convectix.com/img/amd64/amd64/14.2/vmagent/vmagent.img pkg_bootstrap=0 runasap=1
  # cbsd jcreate jname=myapp from=fbbb4e8707f6794008cc6e8ed0d86082 runasap=1
  # cbsd jcreate jname=small flavor=small1 runasap=1 jnameserver="8.8.8.8,8.8.4.4"
+ #[*] cbsd jcreate jname=test ver=empty baserw=1 pkg_bootstrap=0 floatresolv=0 applytpl=0 etcupdate_init=0 from=docker.io/convectix/freebsd14-base
+ #[*] cbsd jcreate jname=test ver=empty baserw=1 pkg_bootstrap=0 floatresolv=0 applytpl=0 etcupdate_init=0 exec_start=/bin/true exec_stop=/bin/true from=docker.io/library/alpine emulator=linux
+
 
 Nice example HOW TO create micro-jail (~8MB, 'busybox' like) with SSH root access:
 
@@ -156,7 +163,6 @@ for i in ${MYOPTARG}; do
 	esac
 done
 
-
 # jcreate global conf
 readconf jcreate.conf
 
@@ -220,7 +226,7 @@ install_and_apply_helpers()
 	local module
 	# shellcheck disable=SC2016
 	# $1 is expanded by awk
-	module=$( cbsdsqlro "${_srcfile}" SELECT helpername FROM system | ${AWK_CMD} '{printf $1}' )
+	module=$( cbsdsqlro "${_srcfile}" "SELECT helpername FROM system ORDER BY helpername ASC" | ${AWK_CMD} '{printf $1}' )
 
 	[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}Install and apply helpers ${_srcfile}: ${N2_COLOR}${module}${N0_COLOR}"
 
@@ -242,7 +248,7 @@ install_and_apply_helpers()
 [ -n "${oflavor}" ] && flavor="${oflavor}"
 if [ -n "${flavor}" ]; then
 	unset ocpu cpu ovmemoryuse vmemoryuse ofsquota fsquota
-	flavors_available=$( cbsdsqlro ${dbdir}/local.sqlite "SELECT name FROM vmpackages" | ${SORT_CMD} | ${XARGS_CMD} )
+	flavors_available=$( cbsdsqlro ${dbdir}/local.sqlite "SELECT name FROM vmpackages ORDER BY name ASC" | ${XARGS_CMD} )
 	flavor_exist=0
 	for i in ${flavors_available}; do
 		[ "${flavor}" = "${i}" ] && flavor_exist=1 && break
@@ -250,7 +256,7 @@ if [ -n "${flavor}" ]; then
 
 	[ ${flavor_exist} -eq 0 ] && log_err 1 "${N1_COLOR}${CBSD_APP}: no such flavor [${flavor}], available flavors: ${N2_COLOR}${flavors_available}${N0_COLOR}"
 
-	_res=$( cbsdsqlro ${dbdir}/local.sqlite "SELECT pkg_vm_cpus,pkg_vm_ram,pkg_vm_disk FROM vmpackages WHERE name=\"${flavor}\" LIMIT 1" 2>/dev/null )
+	_res=$( cbsdsqlro ${dbdir}/local.sqlite "SELECT pkg_vm_cpus,pkg_vm_ram,pkg_vm_disk FROM vmpackages WHERE name='${flavor}' LIMIT 1" 2>/dev/null )
 
 	[ -z "${_res}" ] && log_err 1 "${N1_COLOR}${CBSD_APP}: unable to get vm_cpus/vm_ram/imgsize for flavor: ${N2_COLOR}${flavor}${N0_COLOR}"
 	sqllistdelimer="|"
@@ -269,7 +275,6 @@ if [ -n "${flavor}" ]; then
 
 	unset flavor oflavor flavor_exist flavors_available _res
 fi
-
 
 . ${subrdir}/time.subr
 st_time=$( ${DATE_CMD} +%s )
@@ -338,14 +343,14 @@ if [ -n "${from}" ]; then
 	from_md5=
 
 	# is from=MD5?
-	_res=$( cbsdsqlro images "SELECT source FROM images WHERE md5=\"${from}\"" 2>/dev/null )
+	_res=$( cbsdsqlro images "SELECT md5 FROM images WHERE md5='${from}'" 2>/dev/null )
 	if [ -n "${_res}" ]; then
 		from_md5="${from}"
 	else
 		# second chance - is md5(from) exist?
 		if [ -z "${_res}" ]; then
 			tmpfrom=$( ${miscdir}/cbsd_md5 "${from}" )
-			_res=$( cbsdsqlro images "SELECT source FROM images WHERE md5=\"${tmpfrom}\"" 2>/dev/null )
+			_res=$( cbsdsqlro images "SELECT md5 FROM images WHERE md5='${tmpfrom}'" 2>/dev/null )
 			[ -n "${_res}" ] && from_md5="${tmpfrom}"
 			unset tmpfrom
 		fi
@@ -355,14 +360,21 @@ if [ -n "${from}" ]; then
 
 	if [ -z "${from_md5}" ]; then
 		# cbsd image register ...
-		images mode=register path="${from}"
+		[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}${CBSD_APP}: image not exist, call 'images mode=register': ${N2_COLOR}${from}${N0_COLOR}"
+		if [ "${emulator}" != "jail" ]; then
+			images mode=register path="${from}" platform="${emulator}"
+			ret=$?
+		else
+			images mode=register path="${from}"
+			ret=$?
+		fi
 		ret=$?
 		if [ ${ret} -ne 0 ]; then
-			stderr 1 "${N1_COLOR}${CBSD_APP}: images failed: cbsd images mode=register from=\"${N2_COLOR}\${from}${N1_COLOR}\"${N0_COLOR}"
+			stderr 1 "${N1_COLOR}${CBSD_APP}: images failed (${ret}: cbsd images mode=register from=\"${N2_COLOR}${from}${N1_COLOR}\"${N0_COLOR}"
 		fi
 		tmpfrom=$( ${miscdir}/cbsd_md5 "${from}" )
-		_res=$( cbsdsqlro images "SELECT source FROM images WHERE md5=\"${tmpfrom}\"" 2>/dev/null )
-		[ -z "${_res}" ] && stderr 1 "${N1_COLOR}${CBSD_APP}: images failed: cbsd images mode=register from=\"${N2_COLOR}\${from}${N1_COLOR}\"${N0_COLOR}"
+		_res=$( cbsdsqlro images "SELECT md5 FROM images WHERE md5='${tmpfrom}'" 2>/dev/null )
+		[ -z "${_res}" ] && stderr 1 "${N1_COLOR}${CBSD_APP}: images failed: cbsd images mode=register from=\"${N2_COLOR}${from}${N1_COLOR}\"${N0_COLOR}"
 		from_md5="${tmpfrom}"
 		unset tmpfrom
 	fi
@@ -377,16 +389,28 @@ if [ -n "${from}" ]; then
 		${ZFS_CMD} list -t snapshot ${_zfsssrc_snap} > /dev/null 2>&1
 		_ret=$?
 		if [ ${_ret} -ne 0 ]; then
-			#echo "Create snapshot..."
+			[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}${CBSD_APP}: create snapshot: ${N2_COLOR}${_zfssrc}@start${N0_COLOR}"
 			${ZFS_CMD} snapshot ${_zfssrc}@start
 			${ZFS_CMD} list -t snapshot ${_zfssrc_snap} > /dev/null 2>&1
 			_ret=$?
 			[ ${_ret} -ne 0 ] && stderr 1 "${N1_COLOR}${CBSD_APP}: unable to create snapshot: ${N2_COLOR}${ZFS_CMD} list -t snapshot ${_zfssrc_snap}${N0_COLOR}"
+		else
+			[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}${CBSD_APP}: create snapshot: ${N2_COLOR}${_zfssrc}@start${N0_COLOR}"
 		fi
 
 		[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}create jail from image snapshot: ${N2_COLOR}${_zfssrc_snap}${N0_COLOR}" 1>&2
-		jcreate jname="${jname}" zfs_snapsrc="${_zfssrc_snap}"
+		jcreate jname="${jname}" zfs_snapsrc="${_zfssrc_snap}" ver=empty baserw=1 pkg_bootstrap=0 floatresolv=0 applytpl=0 etcupdate_init=0
 		jail_created=1
+	else
+		[ ! -d "${workdir}/basejail/${from_md5}" ] && err 1 "${N1_COLOR}${CBSD_APP}: no such resources: ${from_md5}: ${N2_COLOR}${workdir}/basejail/${from_md5}${N0_COLOR}"
+		jcreate jname="${jname}" baserw=1 pkg_bootstrap=0 ver=empty etcupdate_init=0 floatresolv=0 applytpl=0
+		. ${subrdir}/rcconf.subr
+		[ $? -eq 1 ] && err 1 "${N1_COLOR}${CBSD_APP}: unable to create jail ${jname} from: ${N2_COLOR}${from}${N0_COLOR}"
+		if [ ! "${data}" ]; then
+			jremove jname="${jname}" > /dev/null 2>&1 || true
+			err 1 "${N1_COLOR}${CBSD_APP}: no such data directory: ${N2_COLOR}${data}${N0_COLOR}"
+		fi
+		${RSYNC_CMD} -a --hard-links --links --acls --xattrs --numeric-ids --recursive --partial --delete ${workdir}/basejail/${from_md5}/ ${data}/
 	fi
 
 	#check for jail exist
@@ -396,7 +420,6 @@ if [ -n "${from}" ]; then
 	. ${temprcconf}
 
 	for i in ${MYOPTARG}; do
-
 		case "${i}" in
 			jname|from|removejconf)
 				continue
diff --git a/tools/images b/tools/images
--- a/tools/images
+++ b/tools/images
@@ -1,7 +1,7 @@
 #!/usr/local/bin/cbsd
 #v13.0.8
 MYARG="mode"
-MYOPTARG="md5 name path source"
+MYOPTARG="md5 name path source platform"
 MYDESC="Manage environment images"
 CBSDMODULE="sys"
 ADDHELP="
@@ -21,6 +21,9 @@ When registering, the image will be unpacked into a separate ZFS dataset
 and a snapshot <dataset>@start will be created. This snapshot will be 
 used as 'zfs_snapsrc=', e.g: 'cbsd jcreate zfs_snapsrc=<dataset>@start ...'
 
+With help of 'buildah' package, you can also receive and register OCI images 
+from the Docker-compatible registry.
+
 ${H3_COLOR}Options${N0_COLOR}:
 
  ${N2_COLOR}mode${N0_COLOR} - can be:
@@ -35,7 +38,10 @@ ${H3_COLOR}Examples${N0_COLOR}:
 
  # cbsd images mode=register name=golds
  # cbsd images mode=register path=/usr/jails/export/golds.img
- # cbsd images mode=register path=\"https://dl.bsdstore.ru/img/amd64/amd64/14.0/redis/redis.img\"
+ # cbsd images mode=register path=\"https://dl.convectix.com/img/amd64/amd64/14.2/redis/redis.img\"
+ # cbsd images mode=register path=docker.io/convectix/freebsd14-base
+ # cbsd images mode=register path=docker.io/library/memcached platform=linux
+ # cbsd images mode=register path=docker.io/library/alpine platform=linux
  # cbsd images mode=list
 
 "
@@ -54,7 +60,7 @@ source=
 # jaildatadir must be set
 get_zfs_image_snap()
 {
-	local _zfssrc _zfssrc_snap
+	local _zfssrc= _zfssrc_snap=
 
 	[ -z "${1}" ] && return 1
 
@@ -89,7 +95,9 @@ get_zfs_image_snap()
 
 images_register()
 {
-	local _md5 _size _ret _res _tmpfile _remove_source=0
+	local _md5= _size= _ret= _res=
+	local _tmpfile= _remove_source=0
+	local _imgname= _imgpath= _buildah_platform=
 
 	[ ! -r ${dbdir}/images.sqlite ] && ${miscdir}/updatesql ${dbdir}/images.sqlite ${distdir}/share/local-images.schema images
 
@@ -103,28 +111,162 @@ images_register()
 		[ ! -r ${path} ] && stderr 1 "${N1_COLOR}${CBSD_APP} error: file not found ${N2_COLOR}${path}${N0_COLOR}"
 	else
 		[ -z "${path}" ] && stderr 1 "${N1_COLOR}${CBSD_APP} error: ${N2_COLOR}path= or name=${N1_COLOR} is mandatory${N0_COLOR}"
-		prefix4=$( substr --pos=0 --len=4 --str="${path}" )
-		# fetch from remote
-		if [ "${prefix4}" = "http" ]; then
-			_md5=$( ${miscdir}/cbsd_md5 "${path}" )
+		_res=$( ${BASENAME_CMD} "${path}" )
+		_ret=0
+		_md5=$( ${miscdir}/cbsd_md5 "${path}" )
+		echo "${_res}" | ${GREP_CMD} -q "\.img$"
+		_ret=$?
+		if [ ${_ret} -eq 0 ]; then
+			# is .img$
+			prefix4=$( substr --pos=0 --len=4 --str="${path}" )
 
-			_res=$( cbsdsqlro images "SELECT source FROM images WHERE md5=\"${_md5}\"" 2>/dev/null )
-			[ -n "${_res}" ] && stderr 1 "${N1_COLOR}${CBSD_APP} error: ${N2_COLOR}${_md5}${N1_COLOR} already exist: source: ${N2_COLOR}${source}${N0_COLOR}"
+			# fetch from remote
+			if [ "${prefix4}" = "http" ]; then
+				_res=$( cbsdsqlro images "SELECT source FROM images WHERE md5='${_md5}'" 2>/dev/null )
+				[ -n "${_res}" ] && stderr 1 "${N1_COLOR}${CBSD_APP} error: ${N2_COLOR}${_md5}${N1_COLOR} already exist, source: ${N2_COLOR}${source}${N0_COLOR}"
+				${ECHO} "${N1_COLOR}${CBSD_APP}: remote resource: ${N2_COLOR}${path}${N0_COLOR}" 1>&2
+				_tmpfile="${importdir}/${_md5}.img"
+				${ECHO} "${N1_COLOR}${CBSD_APP}: ${FETCH_CMD} -o \"${_tmpfile}\" \"${path}\"${N0_COLOR}" 1>&2
+				${FETCH_CMD} -o "${_tmpfile}" "${path}"
+				[ ! -r ${_tmpfile} ] && err 1 "${N1_COLOR}${CBSD_APP} error: unable to fetch: ${N2_COLOR}${path} -> ${_tmpfile}${N0_COLOR}"
+				opath="${path}"
+				_file=$( ${BASENAME_CMD} ${path} )
+				name=$( echo ${_file} | ${SED_CMD} 's:\.img::g' )
+				source="${path}"
+				_omd5="${md5}"
+				path="${_tmpfile}"
+				_remove_source=1
+			fi
+		else
+			if [ -z "${BUILDAH_CMD}" ]; then
+				${ECHO} "${N1_COLOR}${CBSD_APP}: buildah command not found. If ${path} is a registry resource,"
+				${ECHO} "please install package then re-run 'cbsd initenv': ${N2_COLOR}buildah${N0_COLOR}"
+			else
+				${ECHO} "${N1_COLOR}${CBSD_APP}: let's try using the ${BUILDAH_CMD} utility...${N0_COLOR}"
 
-			${ECHO} "${N1_COLOR}${CBSD_APP}: remote resource: ${N2_COLOR}${path}${N0_COLOR}" 1>&2
-			_tmpfile="${importdir}/${_md5}.img"
-			${ECHO} "${N1_COLOR}${CBSD_APP}: ${FETCH_CMD} -o \"${_tmpfile}\" \"${path}\"${N0_COLOR}" 1>&2
-			${FETCH_CMD} -o "${_tmpfile}" "${path}"
-			[ ! -r ${_tmpfile} ] && err 1 "${N1_COLOR}${CBSD_APP} error: unable to fetch: ${N2_COLOR}${path} -> ${_tmpfile}${N0_COLOR}"
-			opath="${path}"
-			_file=$( ${BASENAME_CMD} ${path} )
-			name=$( echo ${_file} | ${SED_CMD} 's:\.img::g' )
-			source="${path}"
-			_omd5="${md5}"
-			path="${_tmpfile}"
-			_remove_source=1
+				# doesn't work? for some reason ignored
+				export XDG_CONFIG_HOME="${workdir}/.config"
+				[ ! -d "${workdir}/basejail/buildah" ] && ${MKDIR_CMD} -p ${workdir}/basejail/buildah
+
+				# --platform linux
+				[ -n "${oplatform}" ] && platform="${oplatform}"
+				_buildah_platform=$( echo ${platform} | ${TR_CMD} '[:upper:]' '[:lower:]' )
+				_imgname=$( ${BUILDAH_CMD} --root ${workdir}/basejail/buildah pull --platform ${_buildah_platform} ${path} 2>/tmp/images.$$ )
+				_ret=$?
+				if [ ${_ret} -ne 0 -o -z "${_imgname}" ]; then
+					${ECHO} "${N1_COLOR}${CBSD_APP}: unable to pull${N0_COLOR}"
+					if [ -r /tmp/images.$$ ]; then
+						${CAT_CMD} /tmp/images.$$
+						${RM_CMD} -f /tmp/images.$$
+					fi
+					exit 1
+				fi
+				[ -r /tmp/images.$$ ] && ${RM_CMD} -f /tmp/images.$$
+				echo "Image name: ${_imgname}"
+				if [ -n "${NOCOLOR}" ]; then
+					${BUILDAH_CMD} --root ${workdir}/basejail/buildah images | ${GREP_CMD} "${path}"
+					_ret=$?
+				else
+					${BUILDAH_CMD} --root ${workdir}/basejail/buildah images | ${ENV_CMD} GREP_COLORS='mt=37;45' GREP_COLOR='37;45' ${GREP_CMD} --colour=always "${path}"
+					_ret=$?
+				fi
+
+				if [ ${_ret} -ne 0 ]; then
+					err 1 "${N1_COLOR}${CBSD_APP}: buildah image not found: ${N2_COLOR}${path}${N0_COLOR}"
+				fi
+
+				echo "${BUILDAH_CMD} --root ${workdir}/basejail/buildah from --name ${_md5} ${_imgname}"
+				_res=$( ${BUILDAH_CMD} --root ${workdir}/basejail/buildah from --name ${_md5} ${_imgname} 2>/tmp/images.$$ )
+				_ret=$?
+				if [ ${_ret} -ne 0 -o -z "${_res}" ]; then
+					${ECHO} "${N1_COLOR}${CBSD_APP}: unable to create buildah container from ${_imgname}${N0_COLOR}"
+					if [ -r /tmp/images.$$ ]; then
+						${CAT_CMD} /tmp/images.$$
+						${RM_CMD} -f /tmp/images.$$
+					fi
+					exit 1
+				fi
+				[ -r /tmp/images.$$ ] && ${RM_CMD} -f /tmp/images.$$
+				echo "image: ${_res}"
+				_imgpath=$( ${BUILDAH_CMD} --root ${workdir}/basejail/buildah mount ${_res} 2>/tmp/images.$$ )
+				_ret=$?
+				if [ ${_ret} -ne 0 -o -z "${_res}" ]; then
+					${ECHO} "${N1_COLOR}${CBSD_APP}: unable to mount buildah container from ${_res}${N0_COLOR}"
+					if [ -r /tmp/images.$$ ]; then
+						${CAT_CMD} /tmp/images.$$
+						${RM_CMD} -f /tmp/images.$$
+					fi
+					exit 1
+				fi
+				[ -r /tmp/images.$$ ] && ${RM_CMD} -f /tmp/images.$$
+				echo "imgpath: ${_imgpath}"
+
+				case "${_buildah_platform}" in
+					freebsd)
+						platform="FreeBSD"
+						;;
+					linux)
+						platform="Linux"
+						;;
+					netbsd)
+						platform="NetBSD"
+						;;
+				esac
+
+				##ZFS
+				if [ ${zfsfeat} -eq 1 ]; then
+					jcreate jname="${_md5}" host_hostname=${_md5}.my.domain ver=empty baserw=1 pkg_bootstrap=0 floatresolv=0 applytpl=0 etcupdate_init=0
+					_ret=$?
+					[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}${CBSD_APP}unable to create jail: ${N2_COLOR}jcreate jname="${_md5}" host_hostname=${_md5}.my.domain${N0_COLOR}"
+					_rootfs="${workdir}/jails-data/${_md5}-data"
+					[ ! -d "${_rootfs}" ] && err 1 "${N1_COLOR}${CBSD_APP}: no data dir for: ${_md5}: ${N2_COLOR}${_rootfs}${N0_COLOR}"
+					junregister jname="${_md5}"
+					${RM_CMD} -f ${jailrcconfdir}/rc.conf_${_md5}
+					# whats about systemdir stuff?
+					${RM_CMD} -rf ${jailsysdir}/${_md5}
+					# create_from_srcsnap loop
+					. ${subrdir}/zfs.subr
+					DATA=$( ${ZFS_CMD} get -Ho value name ${jaildatadir} )
+					${RSYNC_CMD} -z -a --hard-links --links --acls --xattrs --numeric-ids --recursive --partial ${_imgpath}/ ${_rootfs}/
+					_zfssrc="${DATA}/${_md5}"
+					_zfssrc_snap=$( get_zfs_image_snap ${_zfssrc} )
+					# with ZFS we dont need image file anymore
+					[ ${_remove_source} -eq 1 ] && ${RM_CMD} -f ${path}
+					_size=$( ${ZFS_CMD} get -Hp -o value used ${_zfssrc} 2>/dev/null )
+					source="${path}"
+				else
+					# non-ZFS
+					_rootfs="${workdir}/basejail/${_md5}"
+					[ ! -d "${_rootfs}" ] && ${MKDIR_CMD} -p ${_rootfs}
+					${RSYNC_CMD} -z -a --hard-links --links --acls --xattrs --numeric-ids --recursive --partial ${_imgpath}/ ${_rootfs}/
+					sync
+					source="${path}"
+					register_base ver=empty basename="${_md5}" source="${source}" platform="${platform}"
+					_res=$( ${DU_CMD} -sk ${workdir}/basejail/${_md5} | ${AWK_CMD} '{printf $1"k"}' )
+					if is_number ${_res}; then
+						if conv2bytes ${_res}; then
+							_size="${convval}"
+						else
+							_size="0"
+						fi
+					else
+						_size="0"
+					fi
+				fi
+
+				${BUILDAH_CMD} --root ${workdir}/basejail/buildah unmount ${_md5}
+				${BUILDAH_CMD} --root ${workdir}/basejail/buildah rm ${_md5}
+				${BUILDAH_CMD} --root ${workdir}/basejail/buildah rmi ${_imgname}
+
+				[ -z "${emulator}" ] && emulator="jail"
+				[ -z "${name}" ] && name="${path}"
+				[ -z "${source}" ] && source="unknown"
+
+				cbsdsqlrw images "INSERT INTO images ( md5,name,path,source,emulator,size ) VALUES ( '${_md5}', '${name}', '${workdir}/basejail/${_md5}', '${source}', '${emulator}', '${_size}' )"
+				stderr 0 "${N1_COLOR}registered: ${N2_COLOR}${_md5}${N0_COLOR}"
+			fi
 		fi
-		[ ! -r "${path}" ] && stderr 1 "${N1_COLOR}${CBSD_APP} error: file not found ${N2_COLOR}${path}${N0_COLOR}"
+		[ ! -r "${path}" ] && stderr 1 "${N1_COLOR}${CBSD_APP} error: resource not found ${N2_COLOR}${path}${N0_COLOR}"
 		path=$( ${REALPATH_CMD} ${path} )
 
 		if [ -z "${name}" ]; then
@@ -136,7 +278,7 @@ images_register()
 	[ -z "${source}" ] && source="${path}"
 	_md5=$( ${miscdir}/cbsd_md5 "${source}" )
 
-	_res=$( cbsdsqlro images "SELECT source FROM images WHERE md5=\"${_md5}\"" 2>/dev/null )
+	_res=$( cbsdsqlro images "SELECT source FROM images WHERE md5='${_md5}'" 2>/dev/null )
 	[ -n "${_res}" ] && stderr 1 "${N1_COLOR}${CBSD_APP} error: ${N2_COLOR}${_md5}${N1_COLOR} already exist: source: ${N2_COLOR}${source}${N0_COLOR}"
 
 	# detect image emulator
@@ -153,6 +295,8 @@ images_register()
 	# import jail
 	if [ ${zfsfeat} -eq 1 ]; then
 		jimport jname=${path} new_jname=${_md5} host_hostname=${_md5}.my.domain
+		_ret=$?
+		[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}${CBSD_APP}unable to import image: ${N2_COLOR}jimport jname=${path} new_jname=${_md5} host_hostname=${_md5}.my.domain${N0_COLOR}"
 		junregister jname=${_md5}
 		${RM_CMD} -f ${jailrcconfdir}/rc.conf_${_md5}
 		# whats about systemdir stuff?
@@ -164,32 +308,55 @@ images_register()
 		_zfssrc="${DATA}/${_md5}"
 		_zfssrc_snap=$( get_zfs_image_snap ${_zfssrc} )
 
-#		if [ -n "${_zfssrc_snap}" ]; then
-#			. ${temprcconf}
-#			echo "Create from snapshot..."
-#			jcreate jname="${jname}" zfs_snapsrc="${_zfssrc_snap}"
-#			jail_created=1
-#		fi
 		# with ZFS we dont need image file anymore
 		[ ${_remove_source} -eq 1 ] && ${RM_CMD} -f ${path}
+		_size=$( ${ZFS_CMD} get -Hp -o value used ${_zfssrc} 2>/dev/null )
 	else
-		err 1 "${CBSD_APP} for ZFS only"
+		jimport jname=${path} new_jname=${_md5} host_hostname=${_md5}.my.domain
+		_ret=$?
+		[ ${_ret} -ne 0 ] && err 1 "${N1_COLOR}${CBSD_APP}: unable to import image: ${N2_COLOR}jimport jname=${path} new_jname=${_md5} host_hostname=${_md5}.my.domain${N0_COLOR}"
+		if [ ! -d "${workdir}/jails-data/${_md5}-data" ]; then
+			${ECHO} "${N1_COLOR}${CBSD_APP}: no data dir: ${N2_COLOR}${workdir}/jails-data/${_md5}-data${N0_COLOR}"
+			jremove jname=${_md5} || true
+			exit 1
+		fi
+		junregister jname=${_md5}
+		${RM_CMD} -f ${jailrcconfdir}/rc.conf_${_md5}
+		# whats about systemdir stuff?
+		${RM_CMD} -rf ${jailsysdir}/${_md5}
+		[ ! -d "${workdir}/basejail/${_md5}" ] && ${MKDIR_CMD} -p "${workdir}/basejail/${_md5}"
+		[ ! -d "${workdir}/basejail/${_md5}" ] && err 1 "${N1_COLOR}${CBSD_APP}: unable to create basejail dir: ${workdir}/basejail/${_md5}${N0_COLOR}"
+		${ECHO} "${N1_COLOR}${CBSD_APP}: convert image ${_md5} data as basedir: ${N2_COLOR}${workdir}/basejail/${_md5}${N0_COLOR}"
+		${RSYNC_CMD} -a --hard-links --links --acls --xattrs --numeric-ids --recursive --partial --delete ${workdir}/jails-data/${_md5}-data/ ${workdir}/basejail/${_md5}/
+		${CHFLAGS_CMD} noschg ${workdir}/jails-data/${_md5}-data
+		${RM_CMD} -rf noschg ${workdir}/jails-data/${_md5}-data ${workdir}/jails-fstab/${_md5}
+		source="${path}"
+		register_base ver=empty basename="${_md5}" source="${source}"
+		_res=$( ${DU_CMD} -sk ${workdir}/basejail/${_md5} | ${AWK_CMD} '{printf $1"k"}' )
+		if is_number ${_res}; then
+			if conv2bytes ${_res}; then
+				_size="${convval}"
+			else
+				_size="0"
+			fi
+		else
+			_size="0"
+		fi
+		path="${workdir}/basejail/${_md5}"
+		[ -z "${name}" ] && name="${path}"
 	fi
 
-	#_size=$( ${STAT_CMD} -f %z ${path} 2>/dev/null )
-	_size=$( ${ZFS_CMD} get -Hp -o value used ${_zfssrc} 2>/dev/null )
-
 	[ -n "${opath}" ] && path="${opath}"
-	cbsdsqlrw images "INSERT INTO images ( md5,name,path,source,emulator,size ) VALUES ( \"${_md5}\", \"${name}\", \"${path}\", \"${source}\", \"${emulator}\", \"${_size}\" )"
+	cbsdsqlrw images "INSERT INTO images ( md5,name,path,source,emulator,size ) VALUES ( '${_md5}', '${name}', '${path}', '${source}', '${emulator}', '${_size}' )"
 	stderr 0 "${N1_COLOR}registered: ${N2_COLOR}${_md5}${N0_COLOR}"
 }
 
 images_delete()
 {
-	local _res _jaildatadir _data _zfssrc _zfssrc_snap _ret
-	local _data _data_root _jaildatadir_root
+	local _res= _jaildatadir= _data= _zfssrc= _zfssrc_snap= _ret=
+	local _data= _data_root= _jaildatadir_root=
 
-	_res=$( cbsdsqlro images "SELECT source FROM images WHERE md5=\"${md5}\"" 2>/dev/null )
+	_res=$( cbsdsqlro images "SELECT md5 FROM images WHERE md5='${md5}'" 2>/dev/null )
 	[ -z "${_res}" ] && stderr 1 "${N1_COLOR}${CBSD_APP} error: not exist in DB: ${N2_COLOR}${md5}${N0_COLOR}"
 
 	# try to remove ZFS first
@@ -222,11 +389,18 @@ images_delete()
 		else
 			${ECHO} "${N1_COLOR}${CBSD_APP}: dataset not exist: ${N2_COLOR}${ZFS_CMD} get -Ho value name ${_jaildatadir}${N0_COLOR}" 1>&2
 		fi
+	else
+		if [ ! -d "${workdir}/basejail/${md5}" ]; then
+			${ECHO} "${N1_COLOR}${CBSD_APP}: no such directory: ${N2_COLOR}${workdir}/basejail/${md5}${N0_COLOR}"
+		else
+			${CHFLAGS_CMD} noschg ${workdir}/basejail/${md5}
+			${RM_CMD} -rf ${workdir}/basejail/${md5}
+		fi
+		unregister_base ver=empty basename="${md5}" arch='*' target_arch='*' ver='*'
 	fi
 
 	[ -d "${_jaildatadir}" ] && ${RMDIR_CMD} ${_jaildatadir}
-
-	cbsdsqlrw images "DELETE FROM images WHERE md5=\"${md5}\""
+	cbsdsqlrw images "DELETE FROM images WHERE md5='${md5}'"
 	stderr 0 "${N1_COLOR}removed: ${N2_COLOR}${md5}${N0_COLOR}"
 }
 
@@ -241,7 +415,7 @@ case "${mode}" in
 		images_delete
 		;;
 	list)
-		[ -z "${display}" ] && display="md5,name,path,source,emulator,size,created"
+		[ -z "${display}" ] && display="md5,name,path,source,emulator,size"
 		[ -z "${header}" ] && header="1"
 		if [ -n "${jname}" ]; then
 			images-list header="${header}" display="${display}" jname="${jname}"
