sync code

diff --git a/sudoexec/qcreate b/sudoexec/qcreate
--- a/sudoexec/qcreate
+++ b/sudoexec/qcreate
@@ -139,28 +139,37 @@ EXTHELP="wf_qcreate"
 
 . ${subrdir}/nc.subr
 
+nic_flags=
+nic2_flags=
+quiet=0
+
 # temporary hack for second nic
 interface2=
 ci_ip4_addr2=
 ci_gw42=
 ci_interface_mtu2=
 ci_interface2=
+
 readconf buildworld.conf
 readconf zfs.conf
 
-. ${subrdir}/universe.subr
-. ${subrdir}/freebsd_world.subr
-. ${subrdir}/qemu.subr
+oextra_profile_dir=
+extra_profile_dir=
 
 flavor=
 oflavor=
 quiet=0
 oquiet=0
 
+. ${subrdir}/universe.subr
+. ${subrdir}/freebsd_world.subr
+. ${subrdir}/qemu.subr
+
+progress_state_file=
 . ${cbsdinit}
 
 # if some of params specified via args, store them as temporary vars
-for i in ${MYOPTARG}; do
+for i in ${QEMU_ARGS}; do
 	unset o${i}
 	eval "o${i}=\$$i"
 done
@@ -182,42 +191,12 @@ if [ -z "${jconf}" ]; then
 fi
 
 [ -z "${jconf}" -a -z "${jname}" ] && err 1 "${N1_COLOR}Please set for qcreate: ${N2_COLOR}${jconf}${N0_COLOR}"
-
-# map flavor
-[ -n "${oflavor}" ] && flavor="${oflavor}"
-if [ -n "${flavor}" ]; then
-	unset oimgsize imgsize ovm_ram vm_ram ovm_cpus vm_cpus
-	flavors_available=$( cbsdsqlro ${dbdir}/local.sqlite "SELECT name FROM vmpackages" | ${SORT_CMD} | ${XARGS_CMD} )
-	flavor_exist=0
-	for i in ${flavors_available}; do
-		[ "${flavor}" = "${i}" ] && flavor_exist=1 && break
-	done
-
-	[ ${flavor_exist} -eq 0 ] && log_err 1 "${N1_COLOR}${CBSD_APP}: no such flavor [${flavor}], available flavors: ${N2_COLOR}${flavors_available}${N0_COLOR}"
-
-	_res=$( cbsdsqlro ${dbdir}/local.sqlite "SELECT pkg_vm_cpus,pkg_vm_ram,pkg_vm_disk FROM vmpackages WHERE name=\"${flavor}\" LIMIT 1" 2>/dev/null )
-
-	[ -z "${_res}" ] && log_err 1 "${N1_COLOR}${CBSD_APP}: unable to get vm_cpus/vm_ram/imgsize for flavor: ${N2_COLOR}${flavor}${N0_COLOR}"
-	sqllistdelimer="|"
-	sqllist "${_res}" ovm_cpus ovm_ram oimgsize
-	unset sqllistdelimer
-	[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}${CBSD_APP}: flavor ${flavor} -> vm_cpus/vm_ram/imgsize: ${N2_COLOR}[${_res}]${N0_COLOR}"
-
-	[ -z "${ovm_ram}" ] && log_err 1 "${N1_COLOR}${CBSD_APP}: unable to get 'vm_ram' for flavor: ${N2_COLOR}${flavor}${N0_COLOR}"
-	[ -z "${oimgsize}" ] && log_err 1 "${N1_COLOR}${CBSD_APP}: unable to get 'imgsize' for flavor: ${N2_COLOR}${flavor}${N0_COLOR}"
-	[ -z "${ovm_cpus}" ] && log_err 1 "${N1_COLOR}${CBSD_APP}: unable to get 'vm_cpus' for flavor: ${N2_COLOR}${flavor}${N0_COLOR}"
-
-	vm_ram="${ovm_ram}"
-	imgsize="${oimgsize}"
-	vm_cpus="${ovm_cpus}"
-
-	unset flavor oflavor flavor_exist flavors_available _res
-fi
+[ -n "${removejconf}" ] && oremovejconf="${removejconf}"
 
 really_create_base()
 {
 	if [ "${vm_os_type}" = "freebsd" -a "${from_jail}" = "1" ]; then
-		case ${qemu_profile} in
+		case ${vm_os_profile} in
 			"FreeBSD-bsdinstall-jail")
 				export UNAME_r="${ver}-RELEASE"
 				export DISTRIBUTIONS="kernel.txz base.txz"
@@ -232,11 +211,9 @@ really_create_base()
 				init_kerneldir
 				get_base -v ${ver}
 				get_kernel
-				[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}Stage1: ${N2_COLOR}jcreate...${N0_COLOR}"
+				${ECHO} "${N1_COLOR}Stage1: ${N2_COLOR}jcreate...${N0_COLOR}"
+				echo "jcreate jconf=${temprcconf} pkg_bootstrap=0"
 				jcreate jconf=${temprcconf} pkg_bootstrap=0
-
-#				populate_freebsd_world
-#				populate_freebsd_kernel
 				customskel
 				;;
 		esac
@@ -246,6 +223,18 @@ really_create_base()
 really_create_vm()
 {
 	local _res _msg
+
+	# do not create disk
+	[ "${imgtype}" = "none" ] && return 0
+
+	_res=$( substr --pos=0 --len=5 --str=${imgtype} )
+	if [ "${_res}" = "/dev/" ]; then
+		cbsdlogger NOTICE ${CBSD_APP}: bcreate for ${jname}: imgtype = raw: ${imgtype}
+		 [ ! -c "${imgtype}" ] && log_err 1 "${N1_COLOR}${CBSD_APP}: no such character device: ${N2_COLOR}${imgtype}${N0_COLOR}"
+		oimgtype="raw"
+		raw_path_dsk0="${imgtype}"
+		return 0
+	fi
 
 	#test for imgtype
 	case ${zfsfeat} in
@@ -322,8 +311,39 @@ ${CAT_CMD} ${jconf} | ${TR_CMD} -d \\r > ${temprcconf}
 
 [ -z "${jname}" ] && err 1 "${N1_COLOR}${CBSD_APP}: please set: ${N2_COLOR}jname=${N0_COLOR}"
 
+# map flavor
+[ -n "${oflavor}" ] && flavor="${oflavor}"
+if [ -n "${flavor}" ]; then
+	unset oimgsize imgsize ovm_ram vm_ram ovm_cpus vm_cpus
+	flavors_available=$( cbsdsqlro ${dbdir}/local.sqlite "SELECT name FROM vmpackages" | ${SORT_CMD} | ${XARGS_CMD} )
+	flavor_exist=0
+	for i in ${flavors_available}; do
+		[ "${flavor}" = "${i}" ] && flavor_exist=1 && break
+	done
+
+	[ ${flavor_exist} -eq 0 ] && log_err 1 "${N1_COLOR}${CBSD_APP}: no such flavor [${flavor}], available flavors: ${N2_COLOR}${flavors_available}${N0_COLOR}"
+
+	_res=$( cbsdsqlro ${dbdir}/local.sqlite "SELECT pkg_vm_cpus,pkg_vm_ram,pkg_vm_disk FROM vmpackages WHERE name=\"${flavor}\" LIMIT 1" 2>/dev/null )
+
+	[ -z "${_res}" ] && log_err 1 "${N1_COLOR}${CBSD_APP}: unable to get vm_cpus/vm_ram/imgsize for flavor: ${N2_COLOR}${flavor}${N0_COLOR}"
+	sqllistdelimer="|"
+	sqllist "${_res}" ovm_cpus ovm_ram oimgsize
+	unset sqllistdelimer
+	${ECHO} "${N1_COLOR}${CBSD_APP}: flavor ${flavor} -> vm_cpus/vm_ram/imgsize: ${N2_COLOR}[${_res}]${N0_COLOR}"
+
+	[ -z "${ovm_ram}" ] && log_err 1 "${N1_COLOR}${CBSD_APP}: unable to get 'vm_ram' for flavor: ${N2_COLOR}${flavor}${N0_COLOR}"
+	[ -z "${oimgsize}" ] && log_err 1 "${N1_COLOR}${CBSD_APP}: unable to get 'imgsize' for flavor: ${N2_COLOR}${flavor}${N0_COLOR}"
+	[ -z "${ovm_cpus}" ] && log_err 1 "${N1_COLOR}${CBSD_APP}: unable to get 'vm_cpus' for flavor: ${N2_COLOR}${flavor}${N0_COLOR}"
+
+	vm_ram="${ovm_ram}"
+	imgsize="${oimgsize}"
+	vm_cpus="${ovm_cpus}"
+
+	unset flavor oflavor flavor_exist flavors_available _res
+fi
+
 # if some of params specified via args, restore them from temporary vars
-for i in ${MYOPTARG}; do
+for i in ${QEMU_ARGS}; do
 	eval _mytest=\$o$i
 	# Adjust some missed optional args
 	if [ -z "${_mytest}" ]; then
@@ -351,10 +371,8 @@ for i in ${MYOPTARG}; do
 				continue
 				;;
 		esac
-	else
-		/usr/local/cbsd/misc/cbsdsysrc -qf ${temprcconf} ${i}="${_mytest}" > /dev/null 2>&1
-		eval "${i}=${_mytest}"
 	fi
+	/usr/local/cbsd/misc/cbsdsysrc -qf ${temprcconf} ${i}="${_mytest}" > /dev/null 2>&1
 done
 
 jstatus jname=${jname} > /dev/null 2>&1
@@ -368,7 +386,24 @@ vm_os_type=$( echo "${vm_os_type}" | ${TR_CMD} '[:upper:]' '[:lower:]' )
 [ -z "${vm_os_type}" ] && log_err 1 "${N1_COLOR}No such vm_os_type=${N0_COLOR}"
 template_profile=
 template_profile="vm-${vm_os_type}-${vm_os_profile}.conf"
-[ ! -r ${etcdir}/defaults/${template_profile} -a ! -r ${etcdir}/${template_profile} ] && err 1 "${N1_COLOR}${CBSD_APP} error: no such profile: ${N2_COLOR}${template_profile}${N0_COLOR}"
+
+[ -n "${oextra_profile_dir}" ] && extra_profile_dir="${oextra_profile_dir}"
+
+users_template_profile="${etcdir}/${template_profile}"
+
+if [ ! -r ${etcdir}/defaults/${template_profile} -a ! -r ${etcdir}/${template_profile} ]; then
+	[ -z "${extra_profile_dir}" ] && err 1 "${N1_COLOR}${CBSD_APP} error: no such profile: ${N2_COLOR}${template_profile}${N0_COLOR}"
+	if [ -d "${extra_profile_dir}" ]; then
+		if [ -r ${extra_profile_dir}/${template_profile} ]; then
+			users_template_profile="${etcdir}/${template_profile} ${extra_profile_dir}/${template_profile}"
+		else
+			err 1 "${N1_COLOR}${CBSD_APP} error: no such profile: ${N2_COLOR}${template_profile}${N0_COLOR}"
+		fi
+	else
+		${ECHO} "${W1_COLOR}${CBSD_APP} warning: ${N1_COLOR}no such extra_profile_dir: ${N2_COLOR}${extra_profile_dir}${N0_COLOR}" >&2
+		err 1 "${N1_COLOR}${CBSD_APP} error: no such profile: ${N2_COLOR}${template_profile}${N0_COLOR}"
+	fi
+fi
 
 [ -z "${mnt_start}" ] && mnt_start="0"
 
@@ -445,7 +480,7 @@ esac
 
 ${TRUNCATE_CMD} -s0 ${jconf_tmp}
 
-# Merge with default and profile settings
+# Merge with default and profile settings ( users_template_profile can be '${etcdir}/${template_profile}' + '${extra_profile_dir}/${template_profile}"
 for merge_me in ${etcdir}/defaults/qemu-default-default.conf ${etcdir}/defaults/${template_profile} ${etcdir}/qemu-default-default.conf ${etcdir}/${template_profile} ${temprcconf}; do
 	[ ! -r "${merge_me}" ] && continue;
 	tmp_merge=$( ${MKTEMP_CMD} )
@@ -584,10 +619,12 @@ if [ -n "${imgsize_min}" -a -n "${imgsize}" ]; then
 	imgsize_human_mb=$(( imgsize_bytes / 1024 / 1024 ))
 
 	if [ ${imgsize_bytes} -lt ${imgsize_min_bytes} ]; then
-		if [ "${zfsfeat}" = "1" ]; then
-			${ZFS_CMD} destroy ${DATA}/${jname}
-		fi
-		err 1 "${N1_COLOR}imgsize too small: ${N2_COLOR}${imgsize_bytes} ( ${imgsize_human_mb}mb ) < ${imgsize_min_bytes} ( ${imgsize_min_human_mb}mb )${N0_COLOR}"
+		# not fatal?
+#		if [ "${zfsfeat}" = "1" ]; then
+#			${ZFS_CMD} destroy ${DATA}/${jname}
+#		fi
+#		err 1 "${N1_COLOR}imgsize too small: ${N2_COLOR}${imgsize_bytes} ( ${imgsize_human_mb}mb ) < ${imgsize_min_bytes} ( ${imgsize_min_human_mb}mb )${N0_COLOR}"
+		${ECHO} "${W1_COLOR}imgsize too small: ${N2_COLOR}${imgsize_bytes} ( ${imgsize_human_mb}mb ) < ${imgsize_min_bytes} ( ${imgsize_min_human_mb}mb )${N0_COLOR}"
 	fi
 fi
 
@@ -797,14 +834,11 @@ stop.d"
 
 for i in ${system_dir}; do
 	if [ -n "${systemskeldir}" -a "${systemskeldir}/${i}" ]; then
-		if [ -d ${systemskeldir}/${i} ]; then
-			${CP_CMD} -a ${systemskeldir}/${i} ${jailsysdir}/${jname}/${i}
-		else
+		[ ! -d ${jailsysdir}/${jname}/${i} ] && ${MKDIR_CMD} -m 0775 -p ${jailsysdir}/${jname}/${i}
+		${RSYNC_CMD} -az ${systemskeldir}/${i}/ ${jailsysdir}/${jname}/${i}/
+	else
 			[ ${quiet} -ne 1 ] && ${ECHO} "${N1_COLOR}qcreate: warning: no such dir: ${N2_COLOR}${systemskeldir}/${i}${N0_COLOR}"
 			continue
-		fi
-	else
-		[ ! -d "${i}"  ] && ${MKDIR_CMD} -m 0775 -p ${jailsysdir}/${jname}/${i}
 	fi
 	${CHOWN_CMD} ${cbsduser}:${cbsduser} ${jailsysdir}/${jname}/${i}
 done
