fix node mode=add, style

diff --git a/nodectl/node b/nodectl/node
--- a/nodectl/node
+++ b/nodectl/node
@@ -2,19 +2,55 @@
 #v12.0.9
 CBSDMODULE="node"
 MYARG="mode"
-MYOPTARG="node port rootkeyfile cbsdkeyfile pw header allinfo display ip"
+MYOPTARG="allinfo cbsdkeyfile display header ip node port pw rootkeyfile"
 MYDESC="Manipulate or show information for remote nodes"
-ADDHELP="mode = add, remove, list, status\n\
-node = remote node ip or fqdn\n\
-port = ssh port of remote node\n\
-ip = IP address for update\n\
-rootkeyfile = path to id_rsa for root access\n\
-pw = password of cbsd user from remote node (when cbsdkeyfile= is not used)\n\
-cbsdkeyfile = path to cbsd user id_rsa insead of pw\n\
-header = print header in node list\n\
-allinfo = 1 (default) show all info for nodelist, 0 - only nodename\n\
-display= list by comma for column. Default: nodename,ip,port,keyfile,status,idle\n\
-mode=show,update - show or modify details about node\n"
+ADDHELP="
+${H3_COLOR}Description${N0_COLOR}:
+
+This script forces two CBSD nodes to exchange private keys and thus provide each other 
+with password-less access from the 'cbsd' user (who, in fact, has root privileges!) 
+through the OpenSSH service.
+
+This is one of the mechanisms to build a cluster (a group of interconnected computers 
+performing a common function), as opposed to the API-based method.
+
+Connectivity via SSH (peer-to-peer network) and interaction via API 
+(single point of failure/controller one-to-many) are opposite solutions in architecture. 
+
+Each method has its own pros and cons. By default, script use ssh public/private key 
+from the ~cbsd/.ssh directory.
+
+Before adding remote nodes, make sure you copy the public key as 'authorized_keys' on
+remote host:
+
+  cp -a ~cbsd/.ssh/id_rsa.pub ~cbsd/.ssh/authorized_keys
+
+Also, the private key of the remote node will be saved in the ~cbsd/.rssh directory.
+
+${H3_COLOR}Options${N0_COLOR}:
+
+ ${N2_COLOR}allinfo=${N0_COLOR}      - 1 (default) show all info for nodelist, 0 - only nodename
+ ${N2_COLOR}cbsdkeyfile=${N0_COLOR}  - alternative path private key.
+ ${N2_COLOR}display=${N0_COLOR}      - list by comma for column. 
+                 default: nodename,ip,port,keyfile,status,idle
+ ${N2_COLOR}header=${N0_COLOR}       - print header in node list
+ ${N2_COLOR}ip=${N0_COLOR}           - IP address for update
+ ${N2_COLOR}mode=${N0_COLOR}         - add,remove,list,show,update,status - show or modify details about node
+ ${N2_COLOR}node=${N0_COLOR}         - remote node ip or fqdn
+ ${N2_COLOR}port=${N0_COLOR}         - 22 (default), alternative ssh port of remote node
+ ${N2_COLOR}pw=${N0_COLOR}           - password of cbsd user from remote node (when cbsdkeyfile= is not used)
+ ${N2_COLOR}rootkeyfile=${N0_COLOR}  - path to id_rsa for root access
+
+${H3_COLOR}Examples${N0_COLOR}:
+
+ # cbsd node mode=add node=10.0.0.7
+
+${H3_COLOR}See also${N0_COLOR}:
+
+ cbsd rexe --help
+
+"
+
 EXTHELP="wf_node"
 
 . ${subrdir}/nc.subr
@@ -50,24 +86,24 @@ getpw()
 	local oldmodes=$( ${STTY_CMD} -g )
 	pw=""
 
-	trap "stty ${oldmodes}" HUP INT ABRT BUS TERM EXIT
+	trap "${STTY_CMD} ${oldmodes}" HUP INT ABRT BUS TERM EXIT
 
 	printf "${BOLD}Enter password of cbsd user on ${N2_COLOR}${node}${N0_COLOR}${BOLD}:${N0_COLOR} "
 	while [ -z "${pw}" ]; do
-		stty -echo
+		${STTY_CMD} -echo
 		set -e
 		read pw
 		set +e
 	done
 
-	stty ${oldmodes}
+	${STTY_CMD} ${oldmodes}
 	echo
 }
 
 nodeadd()
 {
-	local _res
-	local _myip
+	local _res= _ret=
+	local _myip=
 
 	[ -z "${node}" ] && err 1 "${N1_COLOR}Empty node${N0_COLOR}"
 	[ -z "${port}" ] && port=22
@@ -125,17 +161,19 @@ nodeadd()
 
 	${ECHO} "${N1_COLOR}Connecting to ${node} via ${proto}...${N0_COLOR}"
 	NODENAME=$( ${CBSD_SSH_CMD} /usr/local/bin/cbsd getinfo -q nodename )
-	code=$?
+	_ret=$?
 
-	case ${code} in
+	cbsdlogger NOTICE ${CBSD_APP}: remote node getinfo: ${CBSD_SSH_CMD}
+
+	case ${_ret} in
 		0)
 			${ECHO} "${N1_COLOR}${node} has nodename: ${N2_COLOR}${NODENAME}${N0_COLOR}"
 			;;
 		2)
-			err 1 "${N1_COLOR}Bad password or system user: ${NODENAME}${N0_COLOR}"
+			log_err 1 "${N1_COLOR}Bad password or system user: ${NODENAME}${N0_COLOR}"
 			;;
 		*)
-			err 1 "${N1_COLOR}Connection problem (code ${code}): ${N2_COLOR}${NODENAME}${N0_COLOR}"
+			log_err 1 "${N1_COLOR}Connection problem (_ret ${_ret}): ${N2_COLOR}${NODENAME}${N0_COLOR}"
 			;;
 	esac
 
@@ -151,43 +189,64 @@ nodeadd()
 
 	case ${_res} in
 		0)
-			${ECHO} "${N1_COLOR}Added successful: ${N2_COLOR}${node}${N0_COLOR}"
-			${ECHO} "${W1_COLOR}!Warning! ${H5_COLOR}In a multi-node configuration your commands can be run on remote servers ${W1_COLOR}!Warning!${N0_COLOR}"
-			${ECHO} "${W1_COLOR}!Warning! ${H5_COLOR}Be careful with [xjb]remove-like command ${W1_COLOR}!Warning!${N0_COLOR}"
-			LOCALKEY="${rsshdir}/${MD5NAME}.id_rsa"
-			${TOUCH_CMD} ${rsshdir}/${NODENAME}.node
-			/usr/local/cbsd/misc/cbsdsysrc -qf ${rsshdir}/${NODENAME}.node SSHKEY=${LOCALKEY} > /dev/null
-			/usr/local/cbsd/misc/cbsdsysrc -qf ${rsshdir}/${NODENAME}.node IP=${node} > /dev/null
-			/usr/local/cbsd/misc/cbsdsysrc -qf ${rsshdir}/${NODENAME}.node PORT=${port} > /dev/null
-			${CHOWN_CMD} ${cbsduser} ${rsshdir}/${NODENAME}.node
-			IP=$( cbsdsqlro nodes SELECT ip FROM nodelist WHERE nodename=\"${NODENAME}\" )
-
-			external_exec_master_node_script -a add.d -n ${NODENAME} -i ${node} -p ${port} -k ${LOCALKEY}
-
-			if [ -z "${IP}" ]; then
-				cbsdsqlrw nodes "INSERT INTO nodelist ( nodename, ip, port, keyfile, rootkeyfile, invfile ) VALUES ( \"${NODENAME}\", \"${node}\", \"${port}\", \"${LOCALKEY}\", \"${rootkeyfile}\", \"inv.${NODENAME}.sqlite\" )"
-			else
-				${ECHO} "${N1_COLOR}Already exist in database, updating: ${N2_COLOR}${node}${N0_COLOR}"
-				cbsdsqlrw nodes DELETE FROM nodelist WHERE nodename=\"${NODENAME}\"
-				cbsdsqlrw nodes "INSERT INTO nodelist ( nodename, ip, port, keyfile, rootkeyfile, invfile ) VALUES ( \"${NODENAME}\", \"${node}\", \"${port}\", \"${LOCALKEY}\", \"${rootkeyfile}\", \"inv.${NODENAME}.sqlite\" )"
-			fi
-			idle_update ${NODENAME}
-			retrinv node=${NODENAME} tryoffline=1
-			return ${_res}
+			true
 			;;
 		1)
-			cat ${DEBLOG}
+			if [ -r ${DEBLOG} ]; then
+				${CAT_CMD} ${DEBLOG}
+				${RM_CMD} ${DEBLOG}
+			fi
 			err ${_res} "${N1_COLOR}Error: Bad password${N0_COLOR}"
 			;;
 		2)
-			[ -f "${DEBLOG}" ] && ${CAT_CMD} ${DEBLOG}
+			if [ -r ${DEBLOG} ]; then
+				${CAT_CMD} ${DEBLOG}
+				${RM_CMD} ${DEBLOG}
+			fi
 			err ${_res} "${N1_COLOR}Error: No key found or wrong hostname. Please run: 'cbsd initenv' on remote machine${N0_COLOR}"
 			;;
 		*)
-			cat ${DEBLOG}
+			if [ -r ${DEBLOG} ]; then
+				${CAT_CMD} ${DEBLOG}
+				${RM_CMD} ${DEBLOG}
+			fi
 			err ${_res} "${N1_COLOR}Error: Unkown error${N0_COLOR}"
 			;;
 	esac
+
+	[ -r ${DEBLOG} ] && ${RM_CMD} ${DEBLOG}
+
+	# Copy remote .pub into authorized_keys
+	printf "${N1_COLOR}Update ~cbsd/.ssh/authorized_keys...${N0_COLOR}"
+	${CBSD_SSH_CMD} ${CP_CMD} -a .ssh/id_rsa.pub .ssh/authorized_keys >/dev/null 2>&1
+	_ret=$?
+
+	if [ ${_ret} -ne 0 ]; then
+		err 1 "failed: ${CP_CMD} -a .ssh/id_rsa.pub authorized_keys"
+	fi
+
+	${CAT_CMD} ${DEBLOG}
+	${ECHO} "${W1_COLOR}>>>   !Warning! Please note! !Warning!${N0_COLOR}"
+	${ECHO} "${H5_COLOR}Having a ~cbsd/.ssh/authorized_keys file on ${NODENAME}, anyone who gets private key (~cbsd/.ssh/id_rsa) will have the access from cbsd user!${N0_COLOR}"
+	${ECHO} "${H5_COLOR}In a multi-node configuration your commands can be run on remote servers.${N0_COLOR}"
+	${ECHO} "${H5_COLOR}Be careful with [xjb]remove-like command.${N0_COLOR}"
+	${ECHO} "${W1_COLOR}<<<   !Warning! Please note! !Warning!${N0_COLOR}"
+	LOCALKEY="${rsshdir}/${MD5NAME}.id_rsa"
+	${TOUCH_CMD} ${rsshdir}/${NODENAME}.node
+	/usr/local/cbsd/misc/cbsdsysrc -qf ${rsshdir}/${NODENAME}.node SSHKEY=${LOCALKEY} IP=${node} PORT=${port} > /dev/null
+	${CHOWN_CMD} ${cbsduser} ${rsshdir}/${NODENAME}.node
+	IP=$( cbsdsqlro nodes "SELECT ip FROM nodelist WHERE nodename='${NODENAME}'" )
+	external_exec_master_node_script -a add.d -n ${NODENAME} -i ${node} -p ${port} -k ${LOCALKEY}
+	if [ -z "${IP}" ]; then
+		cbsdsqlrw nodes "INSERT INTO nodelist ( nodename, ip, port, keyfile, rootkeyfile, invfile ) VALUES ( '${NODENAME}', '${node}', '${port}', '${LOCALKEY}', '${rootkeyfile}', 'inv.${NODENAME}.sqlite' )"
+	else
+		${ECHO} "${N1_COLOR}Already exist in database, updating: ${N2_COLOR}${node}${N0_COLOR}"
+		cbsdsqlrw nodes "DELETE FROM nodelist WHERE nodename='${NODENAME}'"
+		cbsdsqlrw nodes "INSERT INTO nodelist ( nodename, ip, port, keyfile, rootkeyfile, invfile ) VALUES ( '${NODENAME}', '${node}', '${port}', '${LOCALKEY}', '${rootkeyfile}', 'inv.${NODENAME}.sqlite' )"
+	fi
+	idle_update ${NODENAME}
+	retrinv node=${NODENAME} tryoffline=1
+	return ${_res}
 }
 
 nodedel()
@@ -262,7 +321,7 @@ shownode() {
 	local _res
 
 	local sqldelimer=" "
-	_res=$( cbsdsqlro nodes SELECT nodename FROM nodelist WHERE nodename=\"${node}\" )
+	_res=$( cbsdsqlro nodes "SELECT nodename FROM nodelist WHERE nodename='${node}'" )
 
 	[ -z "${_res}" ] && err 1 "${N1_COLOR}No such node in databases: ${N2_COLOR}${node}${N0_COLOR}"
 
@@ -297,8 +356,8 @@ shownode() {
 
 	sqldelimer=" "
 
-	local jailsnum=$( cbsdsqlro ${node} SELECT count\(jname\) FROM jails WHERE emulator != \"bhyve\" )
-	local vmsnum=$( cbsdsqlro ${node} SELECT count\(jname\) FROM jails WHERE emulator = \"bhyve\" )
+	local jailsnum=$( cbsdsqlro ${node} "SELECT count\(jname\) FROM jails WHERE emulator != 'bhyve'" )
+	local vmsnum=$( cbsdsqlro ${node} "SELECT count\(jname\) FROM jails WHERE emulator = 'bhyve'" )
 
 	[ -z "${jailsnum}" ] && jailsnum="0"
 	[ -z "${vmsnum}" ] && vmsnum="0"
diff --git a/nodectl/nodeaddkey b/nodectl/nodeaddkey
--- a/nodectl/nodeaddkey
+++ b/nodectl/nodeaddkey
@@ -6,9 +6,7 @@ MYOPTARG="cbsdkeyfile pw"
 MYDESC="Get rsa get from remote node"
 
 . ${subrdir}/nc.subr
-
 . ${cbsdinit}
-
 . ${nodes}
 
 [ -z "${cbsdkeyfile}" -a -z "${pw}" ] && err 1 "${N1_COLOR}nodeaddkey: ${N2_COLOR}pw=${N1_COLOR} or ${N2_COLOR}cbsdkeyfile=${N1_COLOR} is mandatory${N0_COLOR}"
@@ -44,22 +42,31 @@ case ${_ret} in
 	;;
 esac
 
+cbsdlogger NOTICE ${CBSD_APP}: ${CBSD_SFTP_CMD}
 ${CBSD_SFTP_CMD}
-RESULT=$?
+_res=$?
 
-case ${RESULT} in
+[ ! -r "${LOCALKEY}" ] && _res=3
+
+case ${_res} in
 	0)
+		# 0440 also not suitable (for 'cbsd' group, e.g. for 3rd party app)!
 		${CHMOD_CMD} 0400 ${LOCALKEY}
 		${CHOWN_CMD} ${cbsduser}:${cbsduser} ${LOCALKEY}
-		err 0 "${N1_COLOR}Key has been added succesful:${N2_COLOR} ${LOCALKEY}${N0_COLOR}"
+		log_err 0 "${N1_COLOR}Key has been added succesful for ${ip}: ${N2_COLOR}${LOCALKEY}${N0_COLOR}"
 		;;
 	1)
-		err 1 "${N1_COLOR}Bad user or password.${N0_COLOR}"
+		log_err 1 "${N1_COLOR}Bad user or password.${N0_COLOR}"
 		;;
 	2)
-		err 2 "${N1_COLOR}No such key on remote host:${N2_COLOR} ${REMOTEKEY}${N0_COLOR}"
+		log_err 2 "${N1_COLOR}No such key on remote host:${N2_COLOR} ${REMOTEKEY}${N0_COLOR}"
+		;;
+	3)
+		log_err 2 "${N1_COLOR}sftp passed but key not saved: ${N2_COLOR}${REMOTEKEY}${N0_COLOR}"
 		;;
 	*)
-		err 3 "${N1_COLOR}Unknown error.${N0_COLOR}"
+		log_err 3 "${N1_COLOR}Unknown error.${N0_COLOR}"
 		;;
 esac
+
+exit 0
diff --git a/tools/retrinv b/tools/retrinv
--- a/tools/retrinv
+++ b/tools/retrinv
@@ -1,68 +1,110 @@
 #!/usr/local/bin/cbsd
 #v11.2.1
 MYARG=""
-MYOPTARG="node data jname tryoffline"
+MYOPTARG="data jname node tryoffline"
 MYDESC="Fetch sqldb from remote node"
-ADDHELP="when node argument is empty - retrieve db from all nodes from node lists\n\
-data can be - jdescr,nodedescr,db,rctl,fwcnt,bhyve,jail. If not specify - retrieive all of them\n\
-jname - fetch data only for specified jail\n\
-tryoffline=1 - try to fetch inventory when node is offline\n"
+ADDHELP="
+${H3_COLOR}Description${N0_COLOR}:
+
+Receive and save locally system info (e.g. database) from a remote 
+node via a SSH connection.
+
+When 'node' argument is empty - retrieve db from all nodes from node lists.
+
+${H3_COLOR}Options${N0_COLOR}:
+
+ ${N2_COLOR}data=${N0_COLOR}       - which part of info, can be: jdescr,nodedescr,db,rctl,fwcnt,bhyve,jail,qemu,xen. 
+               When not specified - retrieive all of them.
+ ${N2_COLOR}jname=${N0_COLOR}      - fetch data only for specified jail.
+ ${N2_COLOR}tryoffline=${N0_COLOR} - when '1' - try to fetch inventory when node is offline.
+
+${H3_COLOR}Examples${N0_COLOR}:
+
+ # cbsd retrinv
+ # cbsd retrinv node=fnode2.my.domain tryoffline=1 data=db
+
+${H3_COLOR}See also${N0_COLOR}:
+
+ cbsd node --help
+
+"
 
 . ${subrdir}/nc.subr
-
 . ${cbsdinit}
-
 . ${nodes}
 
 retr_db()
 {
-	local _rnode=${1}
+	local _rnode="${1}"
+	local _msg=
 
 	[ -z "${_rnode}" ] && return 0
 
-	nodescp ${checkforonline} ${_rnode}:var/db/inv.${_rnode}.sqlite ${dbdir}/${_rnode}.sqlite && /bin/chmod 0640 "${dbdir}/${_rnode}.sqlite" && /usr/sbin/chown ${cbsduser} "${dbdir}/${_rnode}.sqlite"
+	_cmd="nodescp ${checkforonline} ${_rnode}:var/db/inv.${_rnode}.sqlite ${dbdir}/${_rnode}.sqlite"
+	${_cmd} && ${CHMOD_CMD} 0640 "${dbdir}/${_rnode}.sqlite" && ${CHOWN_CMD} ${cbsduser} "${dbdir}/${_rnode}.sqlite"
 	if [ $? -eq 0 ]; then
 		${ECHO} "${N1_COLOR}CBSD: Fetching inventory done: ${N2_COLOR}${_rnode}${N0_COLOR}"
 		idle_update ${_rnode}
 	else
 		${ECHO} "${N1_COLOR}CBSD: Fetching inventory failed: ${N2_COLOR}${_rnode}${N0_COLOR}"
+		${ECHO} "${N1_COLOR}Guru meditaion: ${N2_COLOR}${_cmd}${N0_COLOR}"
 	fi
+
+	return 0
 }
 
 retr_nodedescr()
 {
-	local _rnode=${1} _files _i
+	local _rnode="${1}" _files= _i=
+	local _res=
+	local _ret=
 
 	[ -z "${_rnode}" ] && return 0
-
-	[ ! -d "${dbdir}/nodedescr" ] && /bin/mkdir -m 0700 -p "${dbdir}/nodedescr" && /bin/chmod 0640 "${dbdir}/nodedescr" && ${cbsduser} "${dbdir}/nodedescr"
+	[ ! -d "${dbdir}/nodedescr" ] && ${MKDIR_CMD} -m 0700 -p "${dbdir}/nodedescr" && ${CHMOD_CMD} 0640 "${dbdir}/nodedescr" && ${cbsduser} "${dbdir}/nodedescr"
 
 	_files="descr role domain notes location"
 
 	for _i in ${_files}; do
-		nodescp ${checkforonline} ${_rnode}:node.${_i} ${dbdir}/nodedescr/${_rnode}.${_i} 2>/dev/null && /bin/chmod 0640 "${dbdir}/nodedescr/${_rnode}.${_i}" && /usr/bin/chown ${cbsduser} "${dbdir}/nodedescr/${_rnode}.${_i}" 2>/dev/null
+		_res=$( nodescp ${checkforonline} ${_rnode}:node.${_i} ${dbdir}/nodedescr/${_rnode}.${_i} 2>/dev/null )
+		_ret=$?
+		if [ ${_ret} -ne 0 ]; then
+			${ECHO} "nodescp failed [skipped]: ${_res}"
+			continue
+		fi
+
+		${CHMOD_CMD} 0640 "${dbdir}/nodedescr/${_rnode}.${_i}" && ${CHOWN_CMD} ${cbsduser} "${dbdir}/nodedescr/${_rnode}.${_i}" 2>/dev/null
 	done
+
+	return 0
 }
 
 # todo: check for shared FS
-retr_bhyve()
+retr_vm()
 {
-	local _rnode=${1} _files _i _sqlfile
-	local _tmpdir
+	local _rnode="${1}" _emulator="${2}"
+	local _files= _i= _sqlfile=
+	local _tmpdir=
 
 	[ -z "${_rnode}" ] && return 0
 
 	_tmpdir="${tmpdir}/${_rnode}"
 
-	[ ! -d ${_tmpdir} ] && /bin/mkdir -p ${_tmpdir}
+	[ ! -d ${_tmpdir} ] && ${MKDIR_CMD} -p ${_tmpdir}
 
-	cbsdsqlro ${_rnode} SELECT jname FROM jails WHERE emulator=\"bhyve\" ORDER BY jname ASC | while read jname; do
-		[ ! -d ${_tmpdir}/${jname} ] && /bin/mkdir -p ${_tmpdir}/${jname}
-
+	cbsdsqlro ${_rnode} SELECT jname FROM jails WHERE emulator='${_emulator}' ORDER BY jname ASC | while read jname; do
+		[ ! -d ${_tmpdir}/${jname} ] && ${MKDIR_CMD} -p ${_tmpdir}/${jname}
 		_files="jails-system/${jname}"
-		nodescp ${checkforonline} ${_rnode}:${_files}/local.sqlite ${_tmpdir}/${jname}/local.sqlite 2>/dev/null
+		_res=$( nodescp ${checkforonline} ${_rnode}:${_files}/local.sqlite ${_tmpdir}/${jname}/local.sqlite 2>/dev/null )
+		_ret=$?
+		if [ ${_ret} -ne 0 ]; then
+			${ECHO} "nodescp failed [skipped]: ${_res}"
+			continue
+		fi
+
 		nodescp ${checkforonline} ${_rnode}:${_files}/vnc_port ${_tmpdir}/${jname}/vnc_port 2>/dev/null
 	done
+
+	return 0
 }
 
 retr_jail()
@@ -73,43 +115,53 @@ retr_jail()
 	[ -z "${_rnode}" ] && return 0
 	_tmpdir="${tmpdir}/${_rnode}"
 
-	[ ! -d ${_tmpdir} ] && /bin/mkdir -p ${_tmpdir}
+	[ ! -d ${_tmpdir} ] && ${MKDIR_CMD} -p ${_tmpdir}
 
+	return 0
 }
 
 
 retr_jdescr()
 {
-	local _rnode=${1} _jname
+	local _rnode="${1}" _jname=
+	local _res=
 
 	[ -z "${_rnode}" ] && return 0
 
 	[ ! -f "${dbdir}/${_rnode}.sqlite" ] && return 0
-	[ ! -d "${dbdir}/nodedescr" ] && /bin/mkdir -p "${dbdir}/nodedescr"
+	[ ! -d "${dbdir}/nodedescr" ] && ${MKDIR_CMD} -p "${dbdir}/nodedescr"
 
-	if [ -z "$jname" ]; then
-		_jname=$( cbsd -c "cbsdsqlro ${_rnode} SELECT jname FROM jails WHERE status\<2" )
+	if [ -z "${jname}" ]; then
+		_jname=$( /usr/local/bin/cbsd -c "cbsdsqlro ${_rnode} SELECT jname FROM jails WHERE status\<2" )
 	else
-		_jname=${jname}
+		_jname="${jname}"
 	fi
 
 	[ -z "${_jname}" ] && return 0
 
 	for _i in ${_jname}; do
-		nodescp ${checkforonline} ${_rnode}:jails-system/${_i}/descr ${dbdir}/nodedescr/${_rnode}.${_i}.descr 2>/dev/null && /bin/chmod 0640 "${dbdir}/nodedescr/${_rnode}.${_i}.descr" && /usr/bin/chown ${cbsduser} "${dbdir}/nodedescr/${_rnode}.${_i}.descr" 2>/dev/null
+		_res=$( nodescp ${checkforonline} ${_rnode}:jails-system/${_i}/descr ${dbdir}/nodedescr/${_rnode}.${_i}.descr 2>/dev/null )
+		_ret=$?
+		if [ ${_ret} -ne 0 ]; then
+			${ECHO} "nodescp failed [skipped]: ${_res}"
+			continue
+		fi
+		${CHMOD_CMD} 0640 "${dbdir}/nodedescr/${_rnode}.${_i}.descr"
+		${CHOWN_CMD} ${cbsduser} "${dbdir}/nodedescr/${_rnode}.${_i}.descr" 2>/dev/null
 	done
 }
 
 retr_rctl()
 {
-	local _rnode=${1} _jname
+	local _rnode="${1}" _jname=
+	local _res=
 
 	[ -z "${_rnode}" ] && return 0
 
 	[ ! -f "${dbdir}/${_rnode}.sqlite" ] && return 0
 
 	if [ -z "$jname" ]; then
-		_jname=$( cbsd -c "cbsdsqlro ${_rnode} SELECT jname FROM jails WHERE status\<2" )
+		_jname=$( /usr/local/bin/cbsd -c "cbsdsqlro ${_rnode} SELECT jname FROM jails WHERE status\<2" )
 	else
 		_jname=${jname}
 	fi
@@ -117,21 +169,30 @@ retr_rctl()
 	[ -z "${_jname}" ] && return 0
 
 	for _i in ${_jname}; do
-		[ ! -d "${dbdir}/rctl/${_rnode}-${_i}" ] && /bin/mkdir -p "${dbdir}/rctl/${_rnode}-${_i}"
-		nodescp ${checkforonline} ${_rnode}:jails-system/${_i}/rctl/* ${dbdir}/rctl/${_rnode}.${_i}.descr 2>/dev/null && /bin/chmod 0640 ${dbdir}/rctl/${_rnode}-${_i}/* && /usr/bin/chown ${cbsduser} ${dbdir}/rctl/${_rnode}-${_i}/* 2>/dev/null
+		[ ! -d "${dbdir}/rctl/${_rnode}-${_i}" ] && ${MKDIR_CMD} -p "${dbdir}/rctl/${_rnode}-${_i}"
+		_res=$( nodescp ${checkforonline} ${_rnode}:jails-system/${_i}/rctl/* ${dbdir}/rctl/${_rnode}.${_i}.descr 2>/dev/null )
+		_ret=$?
+		if [ ${_ret} -ne 0 ]; then
+			${ECHO} "nodescp failed [skipped]: ${_res}"
+			continue
+		fi
+		${CHMOD_CMD} 0640 ${dbdir}/rctl/${_rnode}-${_i}/*
+		${CHOWN_CMD} ${cbsduser} ${dbdir}/rctl/${_rnode}-${_i}/* 2>/dev/null
 	done
+
+	return 0
 }
 
 retr_fwcnt()
 {
-	local _rnode=${1} _jname
+	local _rnode="${1}" _jname=
 
 	[ -z "${_rnode}" ] && return 0
 
 	[ ! -f "${dbdir}/${_rnode}.sqlite" ] && return 0
 
-	if [ -z "$jname" ]; then
-		_jname=$( cbsd -c "cbsdsqlro ${_rnode} SELECT jname FROM jails WHERE status\<2" )
+	if [ -z "${jname}" ]; then
+		_jname=$( /usr/local/bin/cbsd -c "cbsdsqlro ${_rnode} SELECT jname FROM jails WHERE status\<2" )
 	else
 		_jname=${jname}
 	fi
@@ -139,14 +200,23 @@ retr_fwcnt()
 	[ -z "${_jname}" ] && return 0
 
 	for _i in ${_jname}; do
-		[ ! -d "${dbdir}/fwcnt/${_rnode}-${_i}" ] && /bin/mkdir -p "${dbdir}/fwcnt/${_rnode}-${_i}"
-		nodescp ${checkforonline} ${_rnode}:jails-system/${_i}/traffic/* ${dbdir}/fwcnt/${_rnode}-${_i}/ 2>/dev/null && /bin/chmod 0640 ${dbdir}/fwcnt/${_rnode}-${_i}/* && /usr/bin/chown ${cbsduser} ${dbdir}/fwcnt/${_rnode}-${_i}/* 2>/dev/null
+		[ ! -d "${dbdir}/fwcnt/${_rnode}-${_i}" ] && ${MKDIR_CMD} -p "${dbdir}/fwcnt/${_rnode}-${_i}"
+		_res=$( nodescp ${checkforonline} ${_rnode}:jails-system/${_i}/traffic/* ${dbdir}/fwcnt/${_rnode}-${_i}/ 2>/dev/null )
+		_ret=$?
+		if [ ${_ret} -ne 0 ]; then
+			${ECHO} "nodescp failed [skipped]: ${_res}"
+			continue
+		fi
+		${CHMOD_CMD} 0640 ${dbdir}/fwcnt/${_rnode}-${_i}/*
+		${CHOWN_CMD} ${cbsduser} ${dbdir}/fwcnt/${_rnode}-${_i}/* 2>/dev/null
 	done
+
+	return 0
 }
 
 
 # MAIN #
-[ -z "${data}" ] && data="db jdescr nodedescr rctl fwcnt bhyve jail"
+[ -z "${data}" ] && data="db jdescr nodedescr rctl bhyve jail qemu xen"
 if [ -z "${tryoffline}" ]; then
 	tryoffline=0
 	checkforonline="tryoffline=0"
@@ -163,11 +233,10 @@ fi
 # check node online and repopulate array of online nodes if needed
 if [ ${sqlreplica} -eq 1 -a ${tryoffline} -eq 0 ]; then
 	testnode="${node}"
-	node=""
+	node=
 	for i in ${testnode}; do
-		NODEDATA=$( cbsdsqlro nodes select ip,port,keyfile from nodelist where nodename=\"${i}\" )
+		NODEDATA=$( cbsdsqlro nodes "SELECT ip,port,keyfile FROM nodelist WHERE nodename='${i}'" )
 		sqllist "${NODEDATA}" myip myport mykey
-
 		if ! check_locktime ${ftmpdir}/shmux_${myip}.lock >/dev/null 2>&1; then
 			${ECHO} "${N1_COLOR}Node is offline: ${N2_COLOR}${i}${N0_COLOR}"
 			continue
@@ -175,7 +244,6 @@ if [ ${sqlreplica} -eq 1 -a ${tryoffline} -eq 0 ]; then
 		node="${node} ${i}"
 	done
 fi
-
 
 for i in ${node}; do
 	for items in ${data}; do
@@ -195,8 +263,8 @@ for i in ${node}; do
 			fwcnt)
 				retr_fwcnt ${i}
 				;;
-			bhyve)
-				retr_bhyve ${i}
+			bhyve|xen|qemu)
+				retr_vm ${i} ${items}
 				;;
 			jail)
 				retr_jail ${i}
